### ISSUE TITLE
Windows 64 installer fails

### ISSUE THREAD

**Issue by FantasmoX** [dtschump/gmic#275] opened 2020-12-05 18:13 UTC
I tried to install gmic_2.9.4_gimp2.10_win64.exe
When I launch the exe, I immediately get 
"This app cannot be executed on your computer" (blue windows message)
It is a Windows 10 Pro, 64bit, Version 2004

Any advise?

**Comment by imchipbrown** [comment] 2020-12-12 18:55
Same here
![Capture 2020-12-12-36](https://user-images.githubusercontent.com/30630557/101992492-950f3800-3c68-11eb-9e4d-884ab4eb207a.png)

**Comment by FantasmoX** [comment] 2020-12-14 20:27
Hm, no, not same. In your case windows defender interfered, in my case it was a message that indicated that the package is not compatible with the OS

**Comment by FantasmoX** [comment] 2021-01-15 20:17
Anyone?

**Comment by imchipbrown** [comment] 2021-01-15 20:41
I got it to install after finding I could enlarge the message shown above (Windows Protected your PC) which revealed an "Ignore this warning (or some such)" option.

**Comment by FantasmoX** [comment] 2021-01-15 21:18
Funny enough, I downloaded and tried again and it installed without warning whatsoever...
Thanks for the reply anyway!

**Comment by dtschump** [comment] 2021-03-05 10:37
Just in case.. we released version 2.9.6 a few days ago. This probably won't improve the false detection, but this may be something to check. Looks like the issue is solved however, so I close it.
Thanks for your report.

**Closed by dtschump** 2021-03-05 10:37 UTC
