### ISSUE TITLE
Degradation/add grain

### ISSUE THREAD

**Issue by ayachty5** [dtschump/gmic#378] opened 2022-04-13 04:15 UTC
Degradation / add grain does not work.  just get a huge error msg

**Comment by dtschump** [comment] 2022-04-14 08:15
What message?

**Comment by plague-doctor** [comment] 2022-05-25 02:32
I stepped into this issue today... The error when applying:
```
*** Error in ./fx_simulate_grain/__fx_simulate_grain/*repeat/*local/syntexturize/*foreach/ *** Command 'fft': gmicList<float32>::FFT(): Specified real and imaginary parts (897,1269,1,1) have non 2^N dimension along the Y-axis.
```
Pretty much the same on preview (but cannot copy it)...

**Comment by dtschump** [comment] 2022-05-25 05:25
That is a duplicate of https://github.com/dtschump/gmic/issues/384
It comes from the fact your plug-in binary has not been compiled with FFTW support.
Where did you install the plug-in ?

**Comment by dtschump** [comment] 2022-05-25 10:42
Then I think you need to report this to the packagers of Arch Linux.
When building G'MIC, the default configuration enables FFTW. There must be something wrong in the way they packaged it (probably nothing serious that can't be fixed).

**Comment by plague-doctor** [comment] 2022-05-25 10:55
Reported (if anybody would like to add something, here is the link: https://bugs.archlinux.org/index.php?do=details&task_id=74834)

**Comment by dtschump** [comment] 2022-05-25 10:57
Nice! Thanks!

**Closed** 2022-06-11 13:36 UTC
