### ISSUE TITLE
Fedora/GCC 11: More warning output than not...

### ISSUE THREAD

**Issue by hobbes1069** [dtschump/gmic#276] opened 2020-12-11 13:48 UTC
I don't maintain gmic for Fedora but I was rebuilding the package for a new OpenEXR release and noticed that the log file literally has MB of warning output from gcc 11. Most of the output is related to CImg.h:

```
+ make 'OPT_CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -g' NOSTRIP=1 cli lib libc
make "CFLAGS+=-Dgmic_build -Dcimg_date=\\\"\\\" -Dcimg_time=\\\"\\\" -Dcimg_use_zlib -I.    -std=c++11 -pedantic -Wall -Wextra -Wfatal-errors -Werror=unknown-pragmas -Werror=unused-label -Wshadow -Dcimg_use_vt100 -Dcimg_use_abort -Dgmic_is_parallel -Dcimg_use_fftw3  -Dcimg_use_curl  -Dcimg_use_png -I/usr/include/libpng16  -Dcimg_use_jpeg -Dcimg_use_tiff  -fopenmp -Dcimg_use_openmp -Dcimg_display=1   -Dcimg_use_openexr -I/usr/include/OpenEXR -Dcimg_use_opencv -I/usr/include/opencv4  -I/usr/include/opencv -I/usr/include/opencv4  -Ofast -mtune=generic -flto" "LIBS+=-lz   -L/usr/lib -lm -lpthread -lfftw3  -lfftw3_threads -lcurl  -lpng16 -lz  -ljpeg -ltiff  -lgomp -lX11  -lpthread  -lIlmImf -lHalf -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_highgui -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_shape -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_datasets -lopencv_text -lopencv_dnn -lopencv_plot -lopencv_ml -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core   " _cli
make[1]: Entering directory '/builddir/build/BUILD/gmic-2.9.4/src'
g++ -o gmic_cli.o -c gmic.cpp -Dgmic_build -Dcimg_date=\"\" -Dcimg_time=\"\" -Dcimg_use_zlib -I.    -std=c++11 -pedantic -Wall -Wextra -Wfatal-errors -Werror=unknown-pragmas -Werror=unused-label -Wshadow -Dcimg_use_vt100 -Dcimg_use_abort -Dgmic_is_parallel -Dcimg_use_fftw3  -Dcimg_use_curl  -Dcimg_use_png -I/usr/include/libpng16  -Dcimg_use_jpeg -Dcimg_use_tiff  -fopenmp -Dcimg_use_openmp -Dcimg_display=1   -Dcimg_use_openexr -I/usr/include/OpenEXR -Dcimg_use_opencv -I/usr/include/opencv4  -I/usr/include/opencv -I/usr/include/opencv4  -Ofast -mtune=generic -flto
In file included from gmic.h:235,
                 from gmic.cpp:1976:
CImg.h: In member function 'unsigned int cimg_library::CImg<T>::_cimg_math_parser::compile(char*, char*, unsigned int, unsigned int*, bool)':
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:23: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:23: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:23: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:23: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:23: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |                       ^~~~~
CImg.h:16817:3: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:3: note: in definition of macro '_cimg_mp_strerr'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
      |   ^~
CImg.h:16817:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
16817 |   if (*s0==';') ++s0; while (cimg::is_blank(*s0)) ++s0; \
```
Full output here:

https://download.copr.fedorainfracloud.org/results/hobbes1069/openexr/fedora-rawhide-x86_64/01824724-gmic/builder-live.log.gz

**Comment by dtschump** [comment] 2020-12-11 13:57
Thanks. It seems g++11 does too much. It is actually a false warning, but anyway, I've changed the code indentation that should make the warning disappear.
Thanks for the report.

**Comment by hobbes1069** [comment] 2020-12-11 14:02
g++17 is right around the corner... Actually gcc 11 defaults to c++17 but obviously being overridden here.

**Comment by dtschump** [comment] 2021-03-05 10:54
I think the issue is solved. Closing it.

**Closed by dtschump** 2021-03-05 10:54 UTC
