### ISSUE TITLE
G'MIC standalone for windows 64 bits doesn't open JPEG files

### ISSUE THREAD

**Issue by oliveterrad** [dtschump/gmic#308] opened 2021-04-13 09:23 UTC
It seems that the "gmic-2.9.6-qt-win64\gmic_qt.exe" standalone doesn't open JPEG files, only PNG. May this be a local problem related to my own PC, or a general issue ?
![GMIC standalone - screenshot 1](https://user-images.githubusercontent.com/29948074/114529816-a08c6300-9c4a-11eb-8e1c-575cff929495.png)
![GMIC standalone - screenshot 2](https://user-images.githubusercontent.com/29948074/114529834-a5511700-9c4a-11eb-91c1-24057401f725.png)

**Comment by GSib43** [comment] 2021-04-19 10:51
I have the same problem with gmic-2.9.8_pre-qt-win64.
G S

**Comment by dtschump** [comment] 2021-04-19 11:29
Hello. We confirm this problem.

There is something we don't understand though, and we don't know (yet) how to fix that issue.
G'MIC-Qt (standalone) is compiled in a MSYS2 environment, and when launched from there, JPEG files can be opened without issues.

When we put the G'MIC-Qt binaries and its required .dll in a separate folder, and run G'MIC-Qt from there, JPEG files won't open. What we observed is that if we remove the 'Qt5Core.dll' file from the folder, then JPEG can be opened again
(in that case, Qt5Core.dll is taken somewhere else, provided by MSYS2).

It's very strange and we don't have an explanation for this behavior.

If anybody has an idea of what is going on, please let us know!

**Comment by Gpinchon** [comment] 2021-04-21 13:03
> When we put the G'MIC-Qt binaries and its required .dll in a separate folder, and run G'MIC-Qt from there, JPEG files won't open. What we observed is that if we remove the 'Qt5Core.dll' file from the folder, then JPEG can be opened again
> (in that case, Qt5Core.dll is taken somewhere else, provided by MSYS2).

Maybe the version used for the packaging and the version in the Path are different, have you tried fully reinstalling Qt5 ?
What if you manually copy the Qt5Core.dll provided by MSYS2 to the executable folder ?
It could also be somewhat caused by MSYS2 strange behavior with file path, I remember it was the main reason why I migrated several of my projects from MSYS2 to CMake+VS...
Have you tried running in debug mode and check the path used in the open command ?

**Comment by dtschump** [comment] 2021-04-21 13:28
Of course, we used the same .dll for the packaging than the ones provided by MSYS2.
If we copy the Qt5Core.dll in the executable folder, as said in my previous messages, the JPEG files cannot be opened anymore.
It must be something hard-coded in the .dll maybe, I don't know. Another Windows mystery.

**Comment by Gpinchon** [comment] 2021-04-21 16:59
What does QImageReader::supportedImageFormats() return ?
There are several solutions listed in [this thread](https://forum.qt.io/topic/19513/solved-qimage-fail-to-read-jpeg-dll-deploy-problem/13), maybe you could try them ?

**Comment by GSib43** [comment] 2021-04-22 17:48
As in thr thread linked by Gpinchon I copied the folder 'imageformats' with the dlls from my Krita-nightly installation to the Gmic one
and it works! I think the problem were that  'qjpeg.dll' was not available.
Thanks Gpinchon!
G S

**Comment by dtschump** [comment] 2021-04-22 20:58
@GSib43 I did that also but with no luck. JPEG files still cannot be opened with G'MIC-Qt, when I run it from the Windows Command Line (not from MSYS2 shell).

**Comment by GSib43** [comment] 2021-04-23 09:58
Good morning,
please verify the version of the qjpeg.dll you use: I noticed that the versions 5.15.2.0 and 5.12.9.0 work while the 5.12.6.0 doesn't.
My folder's structure is:
D
|-gmic-2.9.8_pre-qt-win64
   |-imageformats (with qjpeg.dll in it)
   |-platforms
   |-styles
   |-gmic_qt.exe
   |-all other dlls
   |-all Qt5 dlls
I hope you can get your fine program running.
G S

**Comment by dtschump** [comment] 2021-04-23 11:22
![gmicqt_jpeg](https://user-images.githubusercontent.com/10114565/115864253-e9a49a00-a436-11eb-9bc4-7bcfcb6030c1.jpg)

Nope, it's 5.15.2.0 here (from MSYS2) and it doesn't work.
Is there a way to replace it with another version, to check ?

**Comment by GSib43** [comment] 2021-04-23 11:53
You can download krita-nightly (the zip package) from here:
https://binary-factory.kde.org/job/Krita_Nightly_Windows_Build/lastBuild/
and then, in the bin folder, you find the 'imageformats' folder with the qjpeg.dll that works (on my system).
G S

**Comment by dtschump** [comment] 2021-04-23 12:44
I confirm this works also here with the .dll from the Krita package.
Great news! Thanks!
I'm going to build a new gmic-qt archive then.

**Comment by GSib43** [comment] 2021-04-23 13:04
Fine!
But someone must understand why.
If change the version of the Qt dlls that you use, maybe that the qjpeg.dll is not anymore usable.
G S

**Comment by dtschump** [comment] 2021-09-02 07:46
As it seems to work right now, I'm closing this issue.

**Closed by dtschump** 2021-09-02 07:46 UTC
