### ISSUE TITLE
GIMP version GIMP 2.10.24 (Revision 2), the plugin gmic no longer works

### ISSUE THREAD

**Issue by alschim** [dtschump/gmic#301] opened 2021-04-04 11:49 UTC
After installing the latest GIMP version, the plugin gmic no longer works.
I use gmic_2.9.6_gimp2.10_win64.exe
Microsoft Windows 10 Pro
Version 20H2 (Build 19042.906)

GIMP 2.10.24 (Revision 2)

When starting GIMP, two error messages appear:

The procedure item "g_memdup2" was not found in the DLL "C:\Program Files\GIMP 2\bin\libgobject-2.0-0.dll".

The procedure item "g_memdup2" was not found in the DLL "C:\Program Files\GIMP 2\bin\libgio-2.0-0.dll".

**Comment by dtschump** [comment] 2021-04-05 07:58
Duplicate of https://github.com/c-koi/gmic-qt/issues/107

**Closed** 2021-09-02 07:49 UTC
